<?xml version="1.0" encoding="UTF-8"?>
<robot rpa="false" generated="20240110 16:50:39.194" schemaversion="2" generator="Robot 4.1.3 (Python 2.7.17 on linux2)">
<suite source="/home/priscila/projetos/curso_udemy/RobotFramework/WebTesting/amazon_testing.robot" id="s1" name="Amazon Testing">
<test id="s1-t1" name="Caso de teste 1 - Acesso ao menu &quot;Mais Vendidos&quot;">
<kw type="SETUP" name="Abrir o navegador" library="amazon_resources">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>browser=${BROWSER}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20240110 16:50:39.309" level="INFO">Opening browser 'chrome' to base url 'None'.</msg>
<status status="PASS" endtime="20240110 16:50:40.768" starttime="20240110 16:50:39.308"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" endtime="20240110 16:50:40.873" starttime="20240110 16:50:40.769"/>
</kw>
<status status="PASS" endtime="20240110 16:50:40.873" starttime="20240110 16:50:39.308"/>
</kw>
<kw name="Acessar a home page do site Amazon.com.br" library="amazon_resources">
<kw name="Go To" library="SeleniumLibrary">
<arg>url=${URL}</arg>
<doc>Navigates the current browser window to the provided ``url``.</doc>
<msg timestamp="20240110 16:50:40.875" level="INFO">Opening url 'https://www.amazon.com.br/'</msg>
<status status="PASS" endtime="20240110 16:50:42.126" starttime="20240110 16:50:40.874"/>
</kw>
<kw name="Wait Until Element Is Visible" library="SeleniumLibrary">
<arg>locator=${MENU_MAIS_VENDIDOS}</arg>
<doc>Waits until the element ``locator`` is visible.</doc>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20240110 16:50:47.574" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))': /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot</msg>
<msg timestamp="20240110 16:50:47.575" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ff4ce58fed0&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot</msg>
<msg timestamp="20240110 16:50:47.576" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ff4ce352050&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot</msg>
<msg timestamp="20240110 16:50:47.582" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=42243): Max retries exceeded with url: /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ff4ce352250&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))</msg>
<status status="FAIL" endtime="20240110 16:50:47.582" starttime="20240110 16:50:47.270"/>
</kw>
<msg timestamp="20240110 16:50:47.582" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=42243): Max retries exceeded with url: /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ff4ce352250&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))</msg>
<msg timestamp="20240110 16:50:47.583" level="FAIL">Element '//a[@href='/gp/bestsellers/?ref_=nav_cs_bestsellers'][contains(.,'Mais Vendidos')]' not visible after 5 seconds.</msg>
<status status="FAIL" endtime="20240110 16:50:47.583" starttime="20240110 16:50:42.127"/>
</kw>
<status status="FAIL" endtime="20240110 16:50:47.585" starttime="20240110 16:50:40.874"/>
</kw>
<kw type="TEARDOWN" name="Fechar o navegador">
<msg timestamp="20240110 16:50:47.593" level="FAIL">No keyword with name 'Fechar o navegador' found.</msg>
<status status="FAIL" endtime="20240110 16:50:47.593" starttime="20240110 16:50:47.593">No keyword with name 'Fechar o navegador' found.</status>
</kw>
<doc>Esse teste verifica o menu "Mais Vendidos" do site da Amazon.com.br
e verifica a categoria "Mais Vendidos em Moda"</doc>
<status status="FAIL" endtime="20240110 16:50:47.593" starttime="20240110 16:50:39.307">Element '//a[@href='/gp/bestsellers/?ref_=nav_cs_bestsellers'][contains(.,'Mais Vendidos')]' not visible after 5 seconds.

Also teardown failed:
No keyword with name 'Fechar o navegador' found.</status>
</test>
<test id="s1-t2" name="Caso de teste 2 - Pesquisa de um Produto">
<doc>Esse teste verifica a busca de um produto</doc>
<status status="FAIL" endtime="20240110 16:50:47.596" starttime="20240110 16:50:47.594">Test case contains no keywords.</status>
</test>
<doc>Essa suite testa o site da amazon.com.br</doc>
<status status="FAIL" endtime="20240110 16:50:47.597" starttime="20240110 16:50:39.195"/>
</suite>
<statistics>
<total>
<stat fail="2" skip="0" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="2" skip="0" id="s1" name="Amazon Testing" pass="0">Amazon Testing</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240110 16:50:47.574" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))': /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot</msg>
<msg timestamp="20240110 16:50:47.575" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ff4ce58fed0&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot</msg>
<msg timestamp="20240110 16:50:47.576" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ff4ce352050&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot</msg>
<msg timestamp="20240110 16:50:47.582" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=42243): Max retries exceeded with url: /session/b055e2732eb1c56b6de73d0c44a8c52a/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ff4ce352250&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))</msg>
</errors>
</robot>
